steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/nuxtjs', '.' ]

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/nuxtjs' ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nuxtjs'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nuxtjs'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west6'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/nuxtjs'
